{% lib "js/shCore.js"
       "js/shBrushAppleScript.js"
       "js/shBrushAS3.js"
       "js/shBrushBash.js"
       "js/shBrushCpp.js"
       "js/shBrushCss.js"
       "js/shBrushErlang.js"
       "js/shBrushJava.js"
       "js/shBrushJScript.js"
       "js/shBrushPerl.js"
       "js/shBrushPhp.js"
       "js/shBrushPlain.js"
       "js/shBrushPython.js"
       "js/shBrushRuby.js"
       "js/shBrushScala.js"
       "js/shBrushSql.js"
       "js/shBrushXml.js"
%}
{% lib "css/shCoreDefault.css" %}
<script>SyntaxHighlighter.all();</script>
